### PR TITLE
draft: check hook function signatures

### PR DESCRIPTION
**Pull request by pdelewski**
fixes https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/81

### CODE REVIEW

**Comment by brettmc** [comment]
I think this is a good idea. I suspect we will want some good tests around the params that can have different types (eg `pre` param #1 could be untyped, or the exact type, or maybe an interface/subtype/supertype). We need to be careful we're not stopping people from using valid code.

**Comment by pdelewski** [comment]
> I think this is a good idea. I suspect we will want some good tests around the params that can have different types (eg `pre` param #1 could be untyped, or the exact type, or maybe an interface/subtype/supertype). We need to be careful we're not stopping people from using valid code.

That's true. I think that we can relax some checks for specific parameters. As you said, the most important thing is to not break user code.

**Comment by lstrojny** [comment]
@brettmc 
> or the exact type, or maybe an interface/subtype/supertype

Don't forget about `mixed`, union and intersection types. It could be easier to just call the function but handle type errors gracefully. That would be my expectation as a user.

**Comment by pdelewski** [comment]
I think that we close this one as https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/79 doing more or less the same thing

**Pull request closed without merging**
