### PR TITLE
install and setup auto-instrumentation with one command

### PR DESCRIPTION
**Pull request by pdelewski**
The goal of this PR is to simplify installation and setup process of auto-instrumentation (https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/28) for specific application and is work in-progress. 
I was considering different approaches to implement this like:

- shell script
- using composer as library
- preparing another composer package that would be a thin layer and group other packages
- PHP CLI application which seems to be most flexible.

Script works in two modes : default and advanced.
Default will install everything without user interaction with latest development version. It will also choose
one of http async client implementation. 
Advanced mode will ask questions about packages, versions and so on.

### CODE REVIEW

**Comment by brettmc** [comment]
This is looking good, I gave it a quick test.

* I think it should be named `bin/install.php`
* there's an off-by-one error when selecting a http client
* It assumes that a composer.json exists, could die with a more helpful message (eg "run composer init first")
* could pre-check for some of our hard requirements, such as ext-otel_instrumentation (and maybe auto-instrumentation is itself a choice?)

**Comment by pdelewski** [comment]
> This is looking good, I gave it a quick test.
> 
> * I think it should be named `bin/install.php`
> * there's an off-by-one error when selecting a http client
> * It assumes that a composer.json exists, could die with a more helpful message (eg "run composer init first")
> * could pre-check for some of our hard requirements, such as ext-otel_instrumentation (and maybe auto-instrumentation is itself a choice?)

I will rename it. I assumed 2 preconditions (have not thought about existence of composer.json, but that's good point):
- PHP installed
- composer installed

I don't think that we need to check existence of ext-otel_instrumentation as one of the goal/step of the script is to install it via pickle for now

**Comment by mikkeschiren** [comment]
If a requirement is pickle - should we also check if pickle is installed?

**Comment by pdelewski** [comment]
> If a requirement is pickle - should we also check if pickle is installed?

Yes. I think that script should download it locally if it's not there yet.

**Comment by pdelewski** [comment]
@brettmc @bobstrecansky Tested that on macOS, linux and windows. Generally it works, except windows where there are problems with building extension out of the box. This at first seems to be a problem with php-sdk as configure script generates wrong code, however I have to check more carefully. 
Still some checks might not work (especially on windows where relative paths are used), other thing is that maybe some of them are redundant as `pickle` will also emit message in the case of error (I just wanted to be more precise and emit better error message :)). There are some other improvements that can be done as getting list of auto-instrumentation packages through packagist API. Having said that, I would like to merge it as it is (if you don't have objections or don't see fundamental problems) and improving it through additional PRs.

**Comment by bobstrecansky** [comment]
Sounds good to me.  Is getting it to work on windows a priority?  If not, we could detect a windows installation and print an error message?

Otherwise sounds good to me.

**Comment by pdelewski** [comment]
> Sounds good to me. Is getting it to work on windows a priority? If not, we could detect a windows installation and print an error message?
> 
> Otherwise sounds good to me.

That's good question if we want to invest time into windows support

**Review by brettmc — APPROVED** [review]

**Pull request merged**
