### PR TITLE
Fix compilation with GCC 10

### PR DESCRIPTION
**Pull request by mlocati**
Close https://github.com/open-telemetry/opentelemetry-php/issues/1260

### CODE REVIEW

**Comment by brettmc** [comment]
The tests still pass, so that's a great start. I'll wait for @agoallikmaa to review as well. Are you able to run clang-format over the code?

**Comment by mlocati** [comment]
> Are you able to run clang-format over the code?

@brettmc Done - see 4b4be3c528ed7e7d0a6067ba84cf99e0db4b72e7

**Comment by brettmc** [comment]
We discussed at SIG and one of our developers thought there might be a cleaner fix, so I'll hold off merging to give them some time to look at it.

**Comment by agoallikmaa** [comment]
Adding `save_state->opline = NULL;` after `save_state->has_opline = false;` should resolve it as well. Should be a more portable solution here as it would help with any static analysis that cannot detect the relation between `opline` and `has_opline` automatically.

**Comment by mlocati** [comment]
What about simply removing `has_opline` and setting `opline` to NULL if there's no opline?

**Comment by agoallikmaa** [comment]
The idea there was to restore the previous value, even if it meant restoring it from a non-null value to `NULL`.

**Comment by brettmc** [comment]
> Adding save_state->opline = NULL; after save_state->has_opline = false; should resolve it as well.

I tested this against `php:8.0-cli-alpine3.13` and it compiled + tests passed, so I've submitted a PR with that change.

**Comment by mlocati** [comment]
Superseded by https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/139

**Pull request closed without merging**
