### PR TITLE
For WINDOWS build!

### PR DESCRIPTION
**Pull request by wantedxnn**

### CODE REVIEW

**Comment by wantedxnn** [comment]
Now extension can be compiled and loaded dynamic(shared) or static (tests 005.phpt and 006.phpt skiped because windows use backslash "\" also the rest tests XFAIL-ed because error is writed in error_log)

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
Thanks for your contribution, @wantedxnn 

> tests 005.phpt and 006.phpt skiped because windows use backslash \

Are you referring to the /'s in the `EXPECTF` output? If that's the only problem, I think you could swap `/`'s for `%c` according to https://qa.php.net/phpt_details.php#expectf_section

Otherwise, I'd be happy to accept this as-is, although I'd like to see windows added to the build matrix in the future.

**Comment by wantedxnn** [comment]
> Thanks for your contribution, @wantedxnn
> 
> > tests 005.phpt and 006.phpt skiped because windows use backslash \
> 
> Are you referring to the /'s in the `EXPECTF` output? If that's the only problem, I think you could swap `/`'s for `%c` according to https://qa.php.net/phpt_details.php#expectf_section
> 
> Otherwise, I'd be happy to accept this as-is, although I'd like to see windows added to the build matrix in the future.



> Thanks for your contribution, @wantedxnn
> 
> > tests 005.phpt and 006.phpt skiped because windows use backslash \
> 
> Are you referring to the /'s in the `EXPECTF` output? If that's the only problem, I think you could swap `/`'s for `%c` according to https://qa.php.net/phpt_details.php#expectf_section
> 
> Otherwise, I'd be happy to accept this as-is, although I'd like to see windows added to the build matrix in the future.

Fixed! used `%e` instead `%c` this will use accordingly OS the corerct separator.

**Review by brettmc — APPROVED** [review]

**Comment by brettmc** [comment]
@wantedxnn are you able to provide some basic instructions/docs on how to build on Windows?

**Comment by wantedxnn** [comment]
Sorry for late response ...
Yes of course!
What do you want more precise to know ?

**Comment by brettmc** [comment]
> Need more details than this?
> https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

If these instructions work for you, then I'm happy to just link to them. Specifically, was it this section? https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions_with_phpize

> Maby can add also github action to build extension for windows

I'd love to have this, otherwise we will accidentally break windows build in the future. I will check it out.

**Comment by brettmc** [comment]
@wantedxnn I added windows build (it's still in my fork only). I see that it fails on 8.0 with Windows. Do you have any ideas about why? https://github.com/brettmc/opentelemetry-php-instrumentation/actions/runs/6386763764/job/17333981115
Otherwise, maybe we can just say "it works on 8.1+"

**Comment by wantedxnn** [comment]
@brettmc I don't used phpize .... I have a very custom php-sdk environment because i compile almost 200 extensions (ported from Linux to windows or upgraded from php5 to php8, all deps are updated to last version also instead compiling in vs16(aka Visual studio 2019) i compile everything  in vs17( aka Visual studio 2022) I have splinted number of extension per build ( 1st build it's only php source as is building snapshot and pgo optimized with avx2 enabled 2nd build all extensions depending by other extension and 3rd build for all non dependending extensions)

But i will try in this evening to build/compile with phpize (i will need to use my artifact development pack from my top described build )

**Comment by wantedxnn** [comment]
@brettmc I see already did PR for windows build action :)
Yes indeed can folow the instruction from wiki.php.net.... will compile the extension flawless :)

**Pull request merged**
