### PR TITLE
moving extension to subdirectory

### PR DESCRIPTION
**Pull request by brettmc**
- move to subdir
- add makefile

### CODE REVIEW

**Comment by brettmc** [comment]
Note that this does break the ability to install from source via `install-php-extensions` - it can't deal with subdirectories. Now that we have PECL, I wouldn't expect much need to install from source?

**Comment by pdelewski** [comment]
> Note that this does break the ability to install from source via `install-php-extensions` - it can't deal with subdirectories. Now that we have PECL, I wouldn't expect much need to install from source?

Yes, that should not be a problem, however IMO https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/AutoInstrumentationInstaller will require some update. I will test it

**Review by bobstrecansky — APPROVED** [review]

**Comment by brettmc** [comment]
> will require some update. I will test it

@pdelewski I will wait for your testing before I merge this. It will also require some updates to the opentelemetry.io docs

**Comment by pdelewski** [comment]
> > will require some update. I will test it
> 
> @pdelewski I will wait for your testing before I merge this. It will also require some updates to the opentelemetry.io docs

@brettmc I made few tests, lgtm. I will update autoinstaller later

**Review by pdelewski — APPROVED** [review]

**Pull request merged**
